INSERT INTO PRODUCT ( BAR_CODE, IS_ACTIVE, NAME, PRICE, TYPE, UOM, IS_PROMO, PROMO_NAME) VALUES ( '100005', true, 'Pringles', 100.0, 'piece', 'pc', false, '');
INSERT INTO PRODUCT ( BAR_CODE, IS_ACTIVE, NAME, PRICE, TYPE, UOM, IS_PROMO, PROMO_NAME) VALUES ( '100006', true, 'Lays', 150.0,'piece', 'pc', false, '');
INSERT INTO PRODUCT (BAR_CODE, IS_ACTIVE, NAME, PRICE, TYPE, UOM, IS_PROMO, PROMO_NAME) VALUES ('100007', true, 'Rice', 50.0, 'bulk', 'kg', false, '');
INSERT INTO PRODUCT (BAR_CODE, IS_ACTIVE, NAME, PRICE, TYPE, UOM, IS_PROMO, PROMO_NAME) VALUES ('100008', true, 'Chicken', 200.0, 'bulk', 'kg', false, '');
INSERT INTO PRODUCT (BAR_CODE, IS_ACTIVE, NAME, PRICE, TYPE, UOM, IS_PROMO, PROMO_NAME) VALUES ('100009', true, 'Snickers', 50.0, 'piece', 'pc', true, 'Buy One Get One Free');
INSERT INTO PRODUCT (BAR_CODE, IS_ACTIVE, NAME, PRICE, TYPE, UOM, IS_PROMO, PROMO_NAME) VALUES ('100010', true, 'Kisses', 50.0, 'piece', 'pc', true, 'Buy Two Get One Free');